### ISSUE TITLE
Interpolations.jl version bump?

### ISSUE THREAD

**Issue by bolognam** [ThummeTo/FMIZoo.jl#14]
Hello,

I'm getting started with running examples from FMIFlux.jl and I'm not able to run the JuliaCon 2023 example with fresh package installs on Julia 1.10.2. It seems that Interpolations.jl is fixed at 0.14.0, and I was not able to find the convenience function `linear_interpolation()` on that version of the code. I'm failing when attempting to load data like this:
```julia
data = VLDM(:train, dt=0.1)
```
It seems that `linear_interpolation()` doesn't exist.

Thanks for the help!

**Comment by ThummeTo** [comment]
Ok, we will check for that

**Comment by 0815Creeper** [comment]
I will look into that
