### ISSUE TITLE
SpringFrictionPendulum1D not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by ufechner7** [ThummeTo/FMIZoo.jl#3]
```
using FMIZoo
pathToFMU = FMIZoo.get_model_filename("SpringFrictionPendulum1D", "Dymola", "2022x")
"/home/ufechner/.julia/packages/FMIZoo/KzRgO/models/bin/Dymola/2022x/2.0/SpringFrictionPendulum1D.fmu"

myFMU = fmiLoad(pathToFMU)
[ Info: fmi2Unzip(...): Successfully unzipped 29 files at `/tmp/fmijl_72yINM/SpringFrictionPendulum1D`.
[ Info: fmi2Load(...): FMU resources location is `file:////tmp/fmijl_72yINM/SpringFrictionPendulum1D/resources`
[ Info: fmi2Load(...): FMU supports both CS and ME, using CS as default if nothing specified.
ERROR: could not load library "/tmp/fmijl_72yINM/SpringFrictionPendulum1D/binaries/linux64/SpringFrictionPendulum1D.so"
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/fmijl_72yINM/SpringFrictionPendulum1D/binaries/linux64/SpringFrictionPendulum1D.so)
Stacktrace:
 [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
   @ Base.Libc.Libdl ./libdl.jl:117
 [2] dlopen (repeats 2 times)
   @ ./libdl.jl:117 [inlined]
 [3] loadBinary(fmu::FMU2)
   @ FMIImport ~/.julia/packages/FMIImport/S8pFT/src/FMI2_ext.jl:210
 [4] fmi2Load(pathToFMU::String; unpackPath::Nothing, type::Nothing)
   @ FMIImport ~/.julia/packages/FMIImport/S8pFT/src/FMI2_ext.jl:197
 [5] fmi2Load
   @ ~/.julia/packages/FMIImport/S8pFT/src/FMI2_ext.jl:101 [inlined]
 [6] #fmiLoad#136
   @ ~/.julia/packages/FMI/pXX2j/src/FMI.jl:228 [inlined]
 [7] fmiLoad(args::String)
   @ FMI ~/.julia/packages/FMI/pXX2j/src/FMI.jl:228
 [8] top-level scope
   @ REPL[13]:1
```
The problem is that the FMI requires GLIBC_2.29, but Ubuntu only comes with GLIBC_2.27 ...

**Comment by ThummeTo** [comment]
Dear @ufechner7,
yes you are right, we are only testing against Ubuntu *latest* (which should be 22.04. LTS I think). We cannot provide FMUs that work with all available OS versions. But: We are working on the possibility to automatically compile OS-dependent FMUs form C-source (which should fix your issue), but this may need some more time until we can provide a stable implementation.

Best regards!

**Comment by ufechner7** [comment]
Well, but this issue could easily be fixed by linking to an older version of glibc because glibc is backwards compatible.
_Despite the long history of compatibility and its almost magical ability to keep old programs running, there is one scenario that compatibility can't solve. You can't run a new program on an old glibc. Well, that's not exactly true. You can build a new program that's intended to run on an old glibc if you have a copy of that old glibc and its headers around. The easiest way to do that is to install an older operating system that has the version of glibc you want, which is the typical advice of "build on the oldest platform you want to support," possibly using a more modern toolset (gcc et al.), such as [Red Hat's Developer Toolset](https://developers.redhat.com/products/developertoolset/overview), which was created for this purpose. That way, the new program depends only on compatibility symbols that are available in that old glibc and any newer glibc. Older glibcs cannot, of course, know the future._

https://developers.redhat.com/blog/2019/08/01/how-the-gnu-c-library-handles-backward-compatibility#plan_ahead

**Comment by ThummeTo** [comment]
I currently have no acceess to a machine running an older version of Ubuntu, but if you want feel free to make a PR

**Comment by ThummeTo** [comment]
Sorry, wrong button :-)

**Comment by ufechner7** [comment]
If you say you have only a build machine with Ubuntu 22.04, this issue could be solved by using a docker container to build the binaries. Can you point me to the build job that is currently creating the binaries?

**Comment by ThummeTo** [comment]
The FMUs are exported (so compiled) from Dymola 2022X, so there is no build job. Unfortunately, the FMUs are not source-code FMUs (no C-source included in the archive), so they can't be build for another platform.

@dafred94 could we replace the current FMUs with source-code FMUs? (this would be a good idea in general)

**Comment by ThummeTo** [comment]
FYI @ufechner7 if we had source code FMUs, you could:

1. Rename the *.fmu with *.zip
2. Unpack
3. Find the source code and makefile inside the archive, build for whatever OS/version you need the FMU

**Comment by ThummeTo** [comment]
Best thing would be to use both I think. The good thing with Dymola is, that it is (almost) always up-to-date with the current FMI-specification (like for example with the new FMI3-release) and we use it in many of our use-cases. As said, I would suggest to use both, FMIZoo.jl provides the ability to add new tools in the folder hierarchy (that is similar to the FMI-crosschecks).

**Comment by ThummeTo** [comment]
we provide source code FMUs in the next release, see branch "sourcecode_fmus"

**Comment by ThummeTo** [comment]
Is this still open @ufechner7 ?

**Comment by ThummeTo** [comment]
Pleasr reopen if necessary.
